name:  Node.js with pm2
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      
    - name: start project
      run: npm start index.js
    
    - name: Install PM2
      run: npm install -g pm2

    - name: Build project (if needed)
      run: npm run build

    - name: Start application with PM2
      run: pm2 start index.js --name "JohnPapa Project"

    - name: Show PM2 process list
      run: pm2 ls
      

     
      

