name: Deploy Node.js with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install PM2
      run: npm install pm2 -g

    - name: Install dependencies
      run: npm install

    - name: Start Node.js application with PM2
      run: pm2 start index.js --name "my-app"

    - name: Show PM2 process list
      run: pm2 list
