name: Node.js CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install PM2
      run: npm install -g pm2

     - name: Install project dependencies
      run: npm install

    - name: Build project (if needed)
      run: npm run build

    - name: Start application with PM2
      run: pm2 start index.js --name "JohnPapa Project"

    - name: Save PM2 process list
      run: pm2 save

    - name: Show PM2 process status
      run: pm2 status
      
      #run: npm ci
    - name: start project
     
